#!/usr/bin/env python3
"""
ELOT AI — Veo 3.1 image-to-video pipeline (tight ~36-second cut).

Takes a hand-picked subset of the marketing screenshots, animates each one
via Vertex AI's Veo 3.1 image-to-video model with **native narration**
generated by Veo itself, then concatenates the six 6-second clips into a
single ~36-second 1280x720 MP4.

Why a separate script from make-video.py?
  - Different shot list (6 scenes, not 18)
  - Different visual engine (real motion via Veo vs static Ken-Burns)
  - Different audio engine (Veo's native voice vs macOS say)
  - Different cost profile (~$25-30 vs $0.10)
  - Different orchestration (async LRO polling per scene)

Env vars:
  GCP_PROJECT        default: `gcloud config get-value project`
  VEO_MODEL          default: veo-3.1-generate-001
                     other:   veo-3.1-fast-generate-001 (~3-4x cheaper)
                              veo-3.0-generate-001
                              veo-2.0-generate-001 (text-only motion)
  VEO_DURATION       seconds per clip, default 6
  VEO_ASPECT         default: 16:9
  POLL_INTERVAL_SEC  default: 8
  POLL_MAX_ITER      default: 60   (max ~8 min per clip)
  DRY_RUN            "1" to skip Veo + use existing clips (debug)

Output:
  artifacts/video/veo/NN-clip.mp4   Veo-generated clip WITH audio
  artifacts/video/elot-veo.mp4      final concatenated video
"""

from __future__ import annotations

import base64
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCREENSHOTS = ROOT / "artifacts" / "screenshots"
OUT_DIR = ROOT / "artifacts" / "video"
VEO_DIR = OUT_DIR / "veo"
FINAL = OUT_DIR / "elot-veo.mp4"

PROJECT = os.environ.get("GCP_PROJECT") or subprocess.check_output(
    ["gcloud", "config", "get-value", "project"], text=True
).strip()
LOCATION = os.environ.get("VEO_LOCATION", "us-central1")
MODEL = os.environ.get("VEO_MODEL", "veo-3.1-generate-001")
DURATION = int(os.environ.get("VEO_DURATION", "6"))
ASPECT = os.environ.get("VEO_ASPECT", "16:9")
POLL_INTERVAL = int(os.environ.get("POLL_INTERVAL_SEC", "8"))
POLL_MAX = int(os.environ.get("POLL_MAX_ITER", "60"))
DRY_RUN = os.environ.get("DRY_RUN") == "1"

# ---------------------------------------------------------------------------
# Tight 6-scene cut. Motion prompts are deliberately understated — Veo will
# add cinematic motion on its own; if we ask for "dramatic" we get artifacts.
# Goal: ~14-22 words per VO so each scene fits inside ~6 seconds of speech.
# ---------------------------------------------------------------------------
@dataclass
class Scene:
    n: int
    image: str   # filename inside artifacts/screenshots/
    motion: str  # Veo prompt — describe motion only, never new content
    vo: str      # voiceover text


SCENES: list[Scene] = [
    Scene(
        n=1,
        image="01-landing.png",
        motion=(
            "very subtle slow camera push-in toward the hero headline, "
            "1.0 to 1.04 zoom, no parallax, UI stays sharp and readable"
        ),
        vo="Hiring takes ninety days. Onboarding burns out managers. "
           "ELOT AI rolls it into one AI-powered platform.",
    ),
    Scene(
        n=2,
        image="07-onboarding-os-hr.png",
        motion=(
            "gentle horizontal camera pan from left to right across the "
            "dashboard, very small movement, dashboard text remains crisp"
        ),
        vo="Every onboarding, every owner, every risk signal. "
           "One screen. No spreadsheets.",
    ),
    Scene(
        n=3,
        image="09-instance-detail.png",
        motion=(
            "soft slow zoom toward the centre of the dashboard, "
            "1.0 to 1.05, smooth and barely perceptible"
        ),
        vo="AI watches every timeline and flags drift before it "
           "costs you the quarter.",
    ),
    Scene(
        n=4,
        image="13-learner-timeline.png",
        motion=(
            "gentle vertical camera tilt downward along the timeline, "
            "subtle parallax, no jitter, UI stays sharp"
        ),
        vo="Day one — new hires see their plan, their team, "
           "and an AI mentor.",
    ),
    Scene(
        n=5,
        image="15-course-builder.png",
        motion=(
            "soft slow camera push-in, very subtle, "
            "with a faint warm bokeh at the edges"
        ),
        vo="Paste any policy. Sixty seconds later, you have an "
           "interactive course.",
    ),
    Scene(
        n=6,
        image="18-admin-dashboard.png",
        motion=(
            "slow zoom out from the dashboard ending slightly wider, "
            "very gentle, ends as a clean wide shot"
        ),
        vo="Real numbers. Real outcomes. This is ELOT AI.",
    ),
]


# Voice direction injected into every Veo prompt so the narrator stays
# consistent across all six generations. Vague prompts give Veo room to
# pick different voices/genders/accents per scene — explicit is better.
NARRATOR = (
    "A confident, warm British male narrator in his early forties, "
    "mid-pace, clear and professional, slightly deeper than average, "
    "no music, no background sound effects, only the narrator's voice. "
    "The narrator speaks naturally with breath, not robotic."
)


def build_prompt(scene: Scene) -> str:
    """Compose the motion + narrator description + dialogue into one prompt.

    Veo 3.x reads everything in `prompt`; there is no separate "narration"
    field. The convention that works best is:
        <visual/motion description>. <voice description>. The narrator
        says: "<dialogue>".
    """
    return (
        f"{scene.motion}. {NARRATOR} "
        f"The narrator says, clearly: \"{scene.vo}\""
    )


# ---------------------------------------------------------------------------
# gcloud auth + REST helpers
# ---------------------------------------------------------------------------
def token() -> str:
    return subprocess.check_output(
        ["gcloud", "auth", "print-access-token"], text=True
    ).strip()


def base_url() -> str:
    return (
        f"https://{LOCATION}-aiplatform.googleapis.com/v1/"
        f"projects/{PROJECT}/locations/{LOCATION}/publishers/google/"
        f"models/{MODEL}"
    )


class QuotaExceeded(Exception):
    """Veo returned 429. Caller may retry with backoff."""


def post_json(url: str, body: dict) -> dict:
    req = urllib.request.Request(
        url,
        data=json.dumps(body).encode("utf-8"),
        method="POST",
        headers={
            "Authorization": f"Bearer {token()}",
            "x-goog-user-project": PROJECT,
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        txt = e.read().decode("utf-8", errors="replace")
        if e.code == 429:
            raise QuotaExceeded(txt)
        sys.exit(f"\nHTTP {e.code} from {url}\n{txt}\n")


# ---------------------------------------------------------------------------
# Veo: submit + poll
# ---------------------------------------------------------------------------
def submit_veo(scene: Scene) -> str:
    """Submit one image-to-video job; return the operation name."""
    img = SCREENSHOTS / scene.image
    if not img.exists():
        sys.exit(f"missing screenshot: {img}")
    b64 = base64.b64encode(img.read_bytes()).decode("ascii")
    body = {
        "instances": [
            {
                "prompt": build_prompt(scene),
                "image": {
                    "bytesBase64Encoded": b64,
                    "mimeType": "image/png",
                },
            }
        ],
        "parameters": {
            "aspectRatio": ASPECT,
            "durationSeconds": DURATION,
            "sampleCount": 1,
            "personGeneration": "allow_adult",
            # Veo 3.x narrates the dialogue we embedded in the prompt. We
            # used to disable audio + lay macOS `say` on top, but that
            # voice was robotic — letting Veo handle it gives a far more
            # natural read at the cost of ~20-30% more generation time.
            "generateAudio": True,
        },
    }
    resp = post_json(f"{base_url()}:predictLongRunning", body)
    op = resp.get("name")
    if not op:
        sys.exit(f"no operation name in submit response: {resp}")
    return op


def poll_veo(op: str) -> dict:
    """Block until the operation is done; return the final response payload."""
    for i in range(1, POLL_MAX + 1):
        resp = post_json(
            f"{base_url()}:fetchPredictOperation",
            {"operationName": op},
        )
        if resp.get("done"):
            if "error" in resp:
                sys.exit(f"Veo operation failed: {resp['error']}")
            return resp.get("response", {})
        print(f"    · polling [{i}/{POLL_MAX}] …", flush=True)
        time.sleep(POLL_INTERVAL)
    sys.exit("Veo poll timed out")


def decode_veo_video(response: dict, out_path: Path) -> None:
    """Veo returns either inline bytes or a GCS URI. Handle both."""
    videos = response.get("videos") or []
    if not videos:
        # Some Veo flavours return under 'predictions'.
        videos = response.get("predictions") or []
    if not videos:
        sys.exit(f"no videos in Veo response: {json.dumps(response)[:500]}")
    vid = videos[0]
    if "bytesBase64Encoded" in vid:
        out_path.write_bytes(base64.b64decode(vid["bytesBase64Encoded"]))
        return
    if "gcsUri" in vid:
        # Fall back to gsutil for GCS-staged output.
        subprocess.run(
            ["gcloud", "storage", "cp", vid["gcsUri"], str(out_path)],
            check=True,
        )
        return
    sys.exit(f"unknown video shape in Veo response: {list(vid.keys())}")


# ---------------------------------------------------------------------------
# ffmpeg concat
# ---------------------------------------------------------------------------
def probe_duration(p: Path) -> float:
    out = subprocess.check_output(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            str(p),
        ],
        text=True,
    )
    return float(out.strip())


def concat_mp4s(clips: list[Path], out: Path) -> None:
    listfile = VEO_DIR / "concat.txt"
    listfile.write_text(
        "".join(f"file '{c.as_posix()}'\n" for c in clips), encoding="utf-8"
    )
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-loglevel",
            "error",
            "-f",
            "concat",
            "-safe",
            "0",
            "-i",
            str(listfile),
            "-vf",
            "fade=t=in:st=0:d=0.4",
            "-af",
            "afade=t=in:st=0:d=0.4",
            "-c:v",
            "libx264",
            "-preset",
            "medium",
            "-crf",
            "20",
            "-c:a",
            "aac",
            "-b:a",
            "192k",
            "-pix_fmt",
            "yuv420p",
            "-movflags",
            "+faststart",
            str(out),
        ],
        check=True,
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    VEO_DIR.mkdir(parents=True, exist_ok=True)

    print(f"[veo] project = {PROJECT}")
    print(f"[veo] model   = {MODEL}  duration={DURATION}s  aspect={ASPECT}")
    print(f"[veo] audio   = native (in-model narration, no external TTS)")
    print(f"[veo] scenes  = {len(SCENES)}\n")

    # 1+2. Serial submit-then-poll per scene with 429 retry. Slower than
    #      parallel (each clip takes 30-90 s to generate) but predictable on
    #      both cost and quota. Veo 2's free quota is roughly 2-3 concurrent
    #      LROs, so any meaningful parallelism trips RESOURCE_EXHAUSTED.
    if not DRY_RUN:
        print("──[1/3] Generate Veo clips (serial) ──────────────────")
        for s in SCENES:
            clip = VEO_DIR / f"{s.n:02d}-clip.mp4"
            if clip.exists():
                print(f"  · scene {s.n}: cached → {clip.name}")
                continue
            # Submit with exponential backoff on 429.
            op: str | None = None
            for attempt in range(6):
                try:
                    op = submit_veo(s)
                    break
                except QuotaExceeded:
                    wait = 30 * (2 ** attempt)
                    print(f"  · scene {s.n}: quota — waiting {wait}s")
                    time.sleep(wait)
            if op is None:
                sys.exit(f"scene {s.n}: gave up after 6 quota retries")
            print(f"  · scene {s.n}: submitted, polling …")
            payload = poll_veo(op)
            decode_veo_video(payload, clip)
            size_kb = clip.stat().st_size / 1024
            print(f"  · scene {s.n}: saved {clip.name} ({size_kb:.0f} KB)")
    else:
        print("[veo] DRY_RUN — using existing clips, skipping Veo")

    # 2. Concat the Veo clips directly. Veo 3.x produced the narration
    #    in-frame, so we skip the macOS `say` + ffmpeg mux step.
    print("\n──[2/2] Concatenate ───────────────────────────────────")
    clips = [VEO_DIR / f"{s.n:02d}-clip.mp4" for s in SCENES]
    concat_mp4s(clips, FINAL)

    total = sum(probe_duration(p) for p in clips)
    size_mb = FINAL.stat().st_size / 1024 / 1024
    print(f"\n[veo] done — {size_mb:.1f} MB, ~{total:.1f}s runtime")
    print(f"[veo] file → {FINAL}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
